# site settings
title: Eunhae Lee
subtitle: Portfolio
email: eunhae@mit.edu
description: welcome to my website
baseurl: /eunhaelee # the subpath of your site, e.g. /blog
url: https://viajeraune.github.io # the base hostname & protocol for your site
author: Eunhae Lee
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 3

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  LinkedIn: https://www.linkedin.com/in/eunhaelee
  Twitter: https://twitter.com/l_eunhae
  GitHub: https://github.com/viajeraune
  GitLab:
  Google-Plus: 
  Instagram:
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
